# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc2fdaa3072865161d24d1bc12cd9978f39b10bbddffe8a78c015031b9fdf5ae1e6785906b467407a9c9f3d2f9198d1e0ba2f056aa32ca644139a40cba4037ac

test:
  secret_key_base: d119e9825b8fe595d2e285da9b056ac5b50ac0d67af0388f2b600dbb7fba45d49ac2f900e3e132069ff3831c193f9a20a9bf4f401236b60ecf2072679a892393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
